#!/bin/bash
#echo >>/tmp/startElf `pwd`
echo >>/tmp/startElf $1
chmod +x $1
gnome-terminal --geometry=90x20+400+300 -x bash -c "/lib64/ld-linux-x86-64.so.2 $1 ; echo Hit Enter to close terminal; read line"
